version: "2"

checks:
  method-complexity:
    config:
      threshold: 12

  method-lines:
    config:
      threshold: 37

  argument-count:
    config:
      threshold: 5

plugins:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          patterns:
            - test/*.js

  csslint:
    enabled: true

  eslint:
    enabled: true

  fixme:
    enabled: true

  nodesecurity:
    enabled: true

  markdownlint:
    enabled: true

  shellcheck:
    enabled: true

  editorconfig:
    enabled: true
    channel: beta

exclude_patterns:
  - .nyc_output/**
  - coverage/**
  - node_modules/**
